return {
    ["accs "] = { text = "accessibility", select = 5 },
    ["acr "] = { text = "accordingly", select = 2 },
    ["actv "] = { text = "activities", select = 2 },
    ["Ang "] = "Angular",
    ["anl "] = "analysis",
    ["apr "] = "approach",
    ["aprt "] = "appropriate",
    ["aprx "] = "approximate",
    ["apt "] = { text = "apparently", select = 2 },
    ["asa "] = "as soon as",
    ["asw "] = "as well as ",
    ["atst "] = "at the same time",
    ["attm"] = "at the moment",
    ["aut "] = { text = "automatically", select = 4 },
    ["avi "] = { text = "availability", select = 5 },
    ["bg "] = "background",
    ["bgn "] = "beginning",
    ["bh "] = "behaviour",
    ["bs "] = "business",
    ["bt "] = "button",
    ["cc "] = "concept",
    ["chr "] = { text = "characteristics", select = 6 },
    ["cll "] = { text = "collection", select = 3 },
    ["cm "] = "comment",
    ["cmd "] = { text = "commands", select = 1 },
    ["cmn "] = { text = "communication", select = 3 },
    ["cmp "] = { text = "components", select = 1 },
    ["cmy "] = "community",
    ["cnd "] = "condition",
    ["cnn "] = "connection",
    ["cnt "] = { text = "contents", select = 1 },
    ["cnv "] = "convenient",
    ["cnx "] = "contextual",
    ["cr "] = "current",
    ["crc "] = { text = "correctly", select = 2 },
    ["crt "] = { text = "certainly", select = 2 },
    ["cst "] = "constraints",
    ["cy "] = "certainlyakey",
    ["dc "] = "document",
    ["dct "] = { text = "directly", select = 2 },
    ["ddd "] = function() return os.date("%d.%m.%Y") end,
    ["dfc "] = "difficult",
    ["dff "] = { text = "different", select = 1 },
    ["dlv "] = "deliverable",
    ["dm "] = { text = "demonstration", select = 3 },
    ["DoD"] = "Definition of Done:",
    ["ds "] = "design",
    ["dsc "] = { text = "description", select = 5 },
    ["dsst"] = "design system",
    ["dvl "] = { text = "development", select = 4 },
    ["ecn "] = "economic",
    ["elm "] = { text = "elements", select = 1 },
    ["env"] = "environment",
    ["ev "] = { text = "evaluation", select = 3 },
    ["exc "] = "excerpt",
    ["exec "] = "expectation",
    ["exm "] = { text = "examples", select = 1 },
    ["exp "] = "experience",
    ["exr "] = "experiment",
    ["fex "] = { text = "for example, ", select = 2 },
    ["fll "] = { text = "following", select = 3 },
    ["fn "] = { text = "functionality", select = 5 },
    ["frq "] = { text = "frequently", select = 2 },
    ["gdl "] = { text = "guidelines", select = 1 },
    ["hf "] = "hopefully",
    ["ht "] = "https://",
    ["imd "] = { text = "immediately", select = 2 },
    ["imp "] = "important",
    ["impl "] = { text = "implementation", select = 5 },
    ["incl "] = "including",
    ["inf "] = "information",
    ["ino "] = "in order to",
    ["intf "] = "interface",
    ["intr "] = "interaction",
    ["inw "] = "interview",
    ["kb "] = "keyboard",
    ["lng "] = { text = "languages", select = 1 },
    ["ly "] = "library",
    ["mb "] = "maybe",
    ["mlt "] = "multiple",
    ["mm "] = { text = "members", select = 1 },
    ["mng "] = "management ",
    ["mnt "] = "mentioned ",
    ["msg "] = "message ",
    ["mt "] = "meeting ",
    ["mth "] = { text = "methodology", select = 5 },
    ["obj "] = "object ",
    ["obs "] = "observation ",
    ["obv "] = { text = "obviously", select = 2 },
    ["pbb "] = function()
        local choices = {
            { text = "probably", select = 1 },
            "maybe",
            "perhaps",
            "possibly"
        }
        return choices[math.random(#choices)]
    end,
    ["plg "] = { text = "plugins", select = 1 },
    ["pls "] = "please ",
    ["pp "] = "people ",
    ["prb "] = "problem",
    ["prc "] = "principle ",
    ["prd "] = { text = "production", select = 3 },
    ["pres "] = "presentation ",
    ["prf "] = { text = "performance", select = 2 },
    ["prj "] = { text = "projects", select = 1 },
    ["prt "] = "prototype",
    ["prtc "] = { text = "participants", select = 1 },
    ["prv "] = "previous ",
    ["psb "] = { text = "possibility", select = 5 },
    ["pwd "] = "password",
    ["qu "] = "question",
    ["res "] = { text = "researching", select = 3 },
    ["rfr "] = { text = "refactoring", select = 3 },
    ["rg "] = "regarding ",
    ["rl "] = "really",
    ["rlb "] = { text = "reliability", select = 5 },
    ["rmm "] = "remember",
    ["rq "] = { text = "requirements", select = 5 },
    ["rs "] = "results",
    ["rso "] = "resources",
    ["rsp "] = { text = "responsible", select = 2 },
    ["sc "] = "screen ",
    ["sco "] = { text = "scenarios", select = 1 },
    ["scr "] = "screenshot ",
    ["sgn "] = "significant ",
    ["sh "] = { text = "shortcuts", select = 1 },
    ["smr "] = "similar ",
    ["smth "] = "something ",
    ["smtm "] = "sometimes ",
    ["sp "] = "separate ",
    ["spc "] = function()
        local choices = {
            { text = "specific", select = 2 },
            "particular"
        }
        return choices[math.random(#choices)]
    end,
    ["spr "] = "spreadsheet ",
    ["ss "] = { text = "systematic", select = 4 },
    ["st "] = "structure",
    ["std "] = { text = "standards", select = 1 },
    ["stg "] = "staging",
    ["sw"] = "software ",
    ["tch "] = { text = "tecnnologies", select = 3 },
    ["thy "] = { text = "Thank you!", moveLeft = 1 },
    ["tmr "] = "tomorrow",
    ["und "] = "understand",
    ["unf "] = "unfortunately",
    ["vr "] = "various",
    ["whth "] = { text = "what do you think, ", moveLeft = 2 },
    ["атт "] = "атрибут",
    ["вар "] = "вариант",
    ["вз "] = { text = "возможно", select = 1 },
    ["вп "] = "вопрос",
    ["втч "] = "в том числе ",
    ["вщ "] = "вообще",
    ["дба "] = "должна быть ",
    ["дбе "] = "должен быть ",
    ["дбо "] = "должно быть ",
    ["дбы "] = "должны быть ",
    ["дв "] = "довольно",
    ["дгв "] = { text = "договорились", select = 3 },
    ["дз "] = "дизайн",
    ["дкм "] = "документ",
    ["дп "] = { text = "дополнительный", select = 2 },
    ["др "] = { text = "другой", select = 2 },
    ["дств "] = "действительно",
    ["едн "] = { text = "единственный", select = 2 },
    ["жл "] = "желательно",
    ["зад "] = { text = "задание", select = 1 },
    ["звт "] = "завтра",
    ["зг "] = { text = "заголовок", select = 2 },
    ["зд "] = "здесь",
    ["здрв "] = "здравствуйте!",
    ["зкр "] = { text = "закрывается", select = 1 },
    ["зн "] = { text = "значение", select = 1 },
    ["имв "] = "имеется в виду",
    ["индв "] = { text = "индивидуальный", select = 2 },
    ["инст "] = "инструмент",
    ["интр "] = { text = "интерактивный", select = 2 },
    ["инф "] = { text = "информационный", select = 5 },
    ["исп "] = { text = "использовать", select = 5 },
    ["итд "] = "и т.д. ",
    ["кк "] = { text = "картинка", select = 1 },
    ["км "] = { text = "комментарий", select = 1 },
    ["кнр "] = { text = "конкретный", select = 2 },
    ["кнт "] = "контент",
    ["колв "] = { text = "количество", select = 1 },
    ["кпр "] = "как правило, ",
    ["крт "] = "кроме того, ",
    ["кт "] = { text = "который", select = 2 },
    ["кц "] = { text = "коммуникация", select = 1 },
    ["лч "] = "лучше",
    ["мб "] = "может быть",
    ["мк "] = "мне кажется, ",
    ["мм "] = "мультимедиа",
    ["нбх "] = { text = "необходимый", select = 2 },
    ["ндм "] = "на данный момент",
    ["нект "] = { text = "некоторый", select = 2 },
    ["необз "] = { text = "необязательный", select = 2 },
    ["нзв "] = "название",
    ["нпв "] = { text = "направление", select = 2 },
    ["нпр "] = "например, ",
    ["нпср "] = "непосредственно ",
    ["нсд "] = "на самом деле ",
    ["нск "] = "несколько",
    ["обз "] = { text = "обязательно", select = 1 },
    ["обр "] = "образом",
    ["однв "] = "одновременно",
    ["опр "] = { text = "определенный", select = 2 },
    ["осб "] = { text = "особенный", select = 2 },
    ["осн "] = { text = "основной", select = 2 },
    ["отд "] = { text = "отдельный", select = 2 },
    ["отн "] = { text = "относительный", select = 8 },
    ["отс "] = { text = "отсутствующий", select = 5 },
    ["офц "] = { text = "официальный", select = 2 },
    ["оч "] = "очень",
    ["очв "] = { text = "очевидно", select = 1 },
    ["пдх "] = { text = "подходящий", select = 2 },
    ["пжл "] = "пожалуйста",
    ["пзв "] = "позволяет",
    ["плз "] = { text = "пользователь", select = 1 },
    ["ппрб "] = { text = "попробовать", select = 3 },
    ["прб "] = "проблема",
    ["прв "] = "правильно",
    ["прг "] = { text = "программа", select = 1 },
    ["прдс "] = "представляет собой",
    ["прдщ "] = { text = "предыдущий", select = 2 },
    ["прмщ "] = { text = "преимущество", select = 1 },
    ["прпд "] = { text = "преподаватель", select = 1 },
    ["прпщ "] = "при помощи",
    ["прс "] = { text = "присутствует", select = 3 },
    ["пск "] = "поскольку",
    ["псл "] = { text = "последний", select = 2 },
    ["псм "] = { text = "посмотреть", select = 2 },
    ["пум "] = "по умолчанию",
    ["резт "] = "результат",
    ["рзл "] = { text = "различный", select = 1 },
    ["рзрб "] = { text = "разработанный", select = 4 },
    ["рск "] = { text = "рассказывает", select = 2 },
    ["рсм "] = { text = "рассматривает", select = 2 },
    ["сбс "] = "собственно",
    ["сбщ "] = { text = "сообщение", select = 1 },
    ["свв "] = { text = "свойство", select = 1 },
    ["свр "] = { text = "современный", select = 2 },
    ["свс "] = "совсем",
    ["сг "] = "сегодня",
    ["сд "] = "сделать",
    ["сй "] = "сейчас",
    ["слд "] = { text = "следующий", select = 2 },
    ["спс "] = "спасибо",
    ["спц "] = { text = "специальный", select = 2 },
    ["срв "] = { text = "средство", select = 1 },
    ["ссл "] = { text = "исследование", select = 2 },
    ["ств "] = { text = "соответственно", select = 4 },
    ["стд "] = { text = "стандартный", select = 2 },
    ["стз "] = "с точки зрения",
    ["стрн "] = { text = "странице", select = 1 },
    ["стц "] = { text = "ситуация", select = 1 },
    ["сч "] = { text = "случай", select = 1 },
    ["сщ "] = { text = "существует", select = 3 },
    ["тж "] = "также",
    ["тк "] = "так как",
    ["тл "] = "только",
    ["тобр "] = "Таким образом, ",
    ["фц "] = { text = "функция", select = 1 },
    ["хрш "] = "хорошо",
    ["чтн "] = "что-нибудь",
    ["чщвс "] = "чаще всего",
    ["эл "] = "элемент",
    ["явл "] = { text = "является", select = 4 },
}
